"use client";

import { NodeViewWrapper, NodeViewContent } from "@tiptap/react";
import { useEffect, useRef, useState } from "react";

// NodeViewContent's `as` prop type uses NoInfer<T> which confuses TS when
// given a literal tag name other than the default "div". Cast to any to
// suppress the false-positive type error while keeping runtime behavior correct.
const NodeViewContentAny = NodeViewContent as any;

export function MermaidBlock({ node }: any) {
  const language = node.attrs.language;
  const code = node.textContent;
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>("");
  const [error, setError] = useState<string>("");
  const [showSource, setShowSource] = useState(false);

  useEffect(() => {
    if (language !== "mermaid" || !code.trim()) {
      setSvg("");
      setError("");
      return;
    }

    let cancelled = false;

    async function render() {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          suppressErrorRendering: true,
          securityLevel: "strict",
          theme: "dark",
          themeVariables: {
            primaryColor: "#2a2a2a",
            primaryTextColor: "#dadada",
            primaryBorderColor: "#3f3f3f",
            lineColor: "#666",
            secondaryColor: "#262626",
            tertiaryColor: "#1e1e1e",
            background: "#1e1e1e",
            mainBkg: "#2a2a2a",
            nodeBorder: "#3f3f3f",
            clusterBkg: "#262626",
            titleColor: "#dadada",
            edgeLabelBackground: "#262626",
          },
          fontFamily: "Inter, sans-serif",
          fontSize: 14,
        });

        const id = `mermaid-${Math.random().toString(36).slice(2, 9)}`;
        const { svg: rendered } = await mermaid.render(id, code);
        if (!cancelled) {
          setSvg(rendered);
          setError("");
        }
      } catch (err: any) {
        if (!cancelled) {
          setError(err?.message || "Invalid mermaid syntax");
          setSvg("");
        }
      }
    }

    render();
    return () => {
      cancelled = true;
    };
  }, [code, language]);

  // Non-mermaid code blocks: render normally
  if (language !== "mermaid") {
    return (
      <NodeViewWrapper className="basemark-editor">
        <pre>
          <NodeViewContentAny as="code" />
        </pre>
      </NodeViewWrapper>
    );
  }

  // Mermaid block
  // Note: svg content comes from mermaid.render() which processes the user's
  // own diagram syntax into a sanitized SVG string. This is the standard
  // pattern used by all mermaid integrations and is safe in this context.
  return (
    <NodeViewWrapper>
      <div className="my-4 rounded-lg border border-border overflow-hidden">
        <div className="flex items-center justify-between px-3 py-1.5 bg-bg-sidebar text-xs text-text-faint">
          <span>mermaid</span>
          <button
            type="button"
            onClick={() => setShowSource(!showSource)}
            className="text-text-faint hover:text-text-primary bg-transparent border-none cursor-pointer text-xs font-inherit"
          >
            {showSource ? "Preview" : "Source"}
          </button>
        </div>

        {showSource ? (
          <pre className="!m-0 !rounded-none">
            <NodeViewContentAny as="code" />
          </pre>
        ) : svg ? (
          /* svg is generated by mermaid.render() from the user's own input — not user-supplied HTML */
          <div
            ref={containerRef}
            className="p-4 flex justify-center bg-bg-primary [&_svg]:max-w-full"
            // eslint-disable-next-line react/no-danger
            dangerouslySetInnerHTML={{ __html: svg }}
          />
        ) : error ? (
          <div className="p-4 text-sm text-danger">{error}</div>
        ) : (
          <div className="p-4 text-sm text-text-faint">Rendering...</div>
        )}
      </div>
    </NodeViewWrapper>
  );
}
